import { useState } from "react";
import type { IRestaurant } from "../types";
import axios from "axios";
import { restaurantService } from "../config";
import toast from "react-hot-toast";
import { BiEdit, BiLogOut, BiMapPin, BiSave } from "react-icons/bi";
import { useAppData } from "../context/AppContext";

const RestaurantProfile = ({ restaurant, isSeller, onUpdate }: { restaurant: IRestaurant; isSeller: boolean; onUpdate: (restaurant: IRestaurant) => void }) => {
  const [editMode,setEditMode]=useState(false); const [name,setName]=useState(restaurant.name); const [description,setDescription]=useState(restaurant.description || ""); const [isOpen,setIsOpen]=useState(restaurant.isOpen); const [loading,setLoading]=useState(false); const {setIsAuth,setUser}=useAppData();
  const headers={Authorization:`Bearer ${localStorage.getItem("token")}`};
  const toggleOpenStatus=async()=>{try{const {data}=await axios.put(`${restaurantService}/api/restaurant/status`,{status:!isOpen,restaurantId:restaurant._id},{headers}); setIsOpen(data.restaurant.isOpen); onUpdate({...restaurant,isOpen:data.restaurant.isOpen}); toast.success(data.restaurant.isOpen?"Restaurant is open":"Restaurant is closed");}catch(error){toast.error(axios.isAxiosError(error)?error.response?.data?.message||"Could not update status":"Could not update status");}};
  const saveChanges=async()=>{if(!name.trim()){toast.error("Restaurant name is required");return;}try{setLoading(true);const {data}=await axios.put(`${restaurantService}/api/restaurant/edit`,{restaurantId:restaurant._id,name:name.trim(),description:description.trim()},{headers});onUpdate(data.restaurant);setEditMode(false);toast.success("Restaurant updated");}catch{toast.error("Failed to update restaurant");}finally{setLoading(false);}};
  const logoutHandler=async()=>{try{if(isOpen)await axios.put(`${restaurantService}/api/restaurant/status`,{status:false,restaurantId:restaurant._id},{headers});}catch(error){console.error(error);}finally{localStorage.removeItem("token");setIsAuth(false);setUser(null);toast.success("Logged out");}};
  return <section className="cm-card overflow-hidden"><div className="relative h-56 bg-[#0b0f15] sm:h-64">{restaurant.image&&<img src={restaurant.image} alt={restaurant.name} className="h-full w-full object-cover"/>}<div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-transparent"/><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between gap-4 text-white"><div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${restaurant.isVerified?"bg-emerald-500/100":"bg-amber-500/100"}`}>{restaurant.isVerified?"Verified partner":"Verification pending"}</span><h1 className="mt-2 text-3xl font-black tracking-tight">{restaurant.name}</h1></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${isOpen?"bg-emerald-500/100":"bg-slate-700"}`}>{isOpen?"Open":"Closed"}</span></div></div><div className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div className="min-w-0 flex-1">{editMode?<input className="cm-input text-lg font-bold" value={name} onChange={(e)=>setName(e.target.value)}/>:<p className="text-sm font-semibold text-slate-400">Restaurant profile</p>}<p className="mt-2 flex items-start gap-2 text-sm text-slate-400"><BiMapPin className="mt-0.5 shrink-0 text-orange-500"/>{restaurant.autoLocation?.formattedAddress||"Location unavailable"}</p></div>{isSeller&&<button onClick={()=>setEditMode(!editMode)} className="cm-secondary !p-2.5" aria-label="Edit restaurant"><BiEdit/></button>}</div>{editMode?<textarea className="cm-input mt-4 min-h-24" value={description} onChange={(e)=>setDescription(e.target.value)}/>:<p className="mt-4 text-sm leading-6 text-slate-400">{restaurant.description||"Add a short description to help customers know your restaurant."}</p>}<div className="mt-5 flex flex-wrap gap-3 border-t border-white/10 pt-5">{editMode&&<button onClick={saveChanges} disabled={loading} className="cm-primary"><BiSave/>{loading?"Saving...":"Save profile"}</button>}{isSeller&&<button onClick={toggleOpenStatus} className={isOpen?"cm-secondary":"cm-primary"}>{isOpen?"Close restaurant":"Open restaurant"}</button>}{isSeller&&<button onClick={logoutHandler} className="cm-secondary ml-auto"><BiLogOut/>Logout</button>}</div></div></section>;
};
export default RestaurantProfile;
