import axios from "axios";
import type { IOrder } from "../types";
import { riderService } from "../config";
import toast from "react-hot-toast";
import { useState } from "react";
import { BiMapPin, BiPhone, BiRupee, BiStore } from "react-icons/bi";

const RiderCurrentOrder=({order,onStatusUpdate}:{order:IOrder;onStatusUpdate:()=>void})=>{const [updating,setUpdating]=useState(false);const updateStatus=async()=>{try{setUpdating(true);const {data}=await axios.put(`${riderService}/api/rider/order/update/${order._id}`,{}, {headers:{Authorization:`Bearer ${localStorage.getItem("token")}`}});toast.success(data.message||"Order updated");onStatusUpdate();}catch(error){toast.error(axios.isAxiosError(error)?error.response?.data?.message||"Could not update order":"Could not update order");}finally{setUpdating(false);}};return <article className="cm-card p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-orange-500">Current delivery</p><div className="mt-2 flex items-center justify-between gap-3"><h2 className="text-xl font-black text-slate-100">Order #{order._id.slice(-6).toUpperCase()}</h2><span className="rounded-full bg-orange-500/10 px-2.5 py-1 text-xs font-bold capitalize text-orange-700">{order.status.replaceAll("_"," ")}</span></div><div className="mt-5 space-y-4"><div className="flex gap-3"><BiStore className="mt-0.5 shrink-0 text-xl text-orange-500"/><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Pickup</p><p className="mt-1 text-sm font-bold text-slate-200">{order.restaurantName}</p></div></div><div className="flex gap-3"><BiMapPin className="mt-0.5 shrink-0 text-xl text-orange-500"/><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Drop</p><p className="mt-1 text-sm font-semibold leading-5 text-slate-300">{order.deliveryAddress.fromattedAddress}</p></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#11161d] p-3"><p className="text-xs text-slate-400">Order value</p><p className="mt-1 font-black text-slate-100">₹{order.totalAmount}</p></div><div className="rounded-2xl bg-emerald-500/10 p-3"><p className="text-xs text-emerald-700">Your earning</p><p className="mt-1 flex items-center font-black text-emerald-800"><BiRupee/>{order.riderAmount}</p></div></div>{order.deliveryAddress.mobile&&<a href={`tel:${order.deliveryAddress.mobile}`} className="cm-secondary w-full"><BiPhone/>Call customer · {order.deliveryAddress.mobile}</a>}</div>{order.status==="rider_assigned"&&<button disabled={updating} onClick={updateStatus} className="cm-primary mt-5 w-full">{updating?"Updating...":"Confirm pickup"}</button>}{order.status==="picked_up"&&<button disabled={updating} onClick={updateStatus} className="cm-primary mt-5 w-full">{updating?"Updating...":"Mark delivered"}</button>}</article>;};
export default RiderCurrentOrder;
