import { useEffect, useRef, useState } from "react";
import { useAppData } from "../context/AppContext";
import { useSocket } from "../context/SocketContext";
import axios from "axios";
import { riderService } from "../config";
import toast from "react-hot-toast";
import { BiBell, BiCheckShield, BiCycling, BiImageAdd, BiLogOut, BiMapPin } from "react-icons/bi";
import type { IOrder } from "../types";
import audio from "../assets/faaah.mp3";
import RiderOrderRequest from "../components/RiderOrderRequest";
import RiderCurrentOrder from "../components/RiderCurrentOrder";
import RiderOrderMap from "../components/RiderOrderMap";
import BrandLogo from "../components/BrandLogo";

interface IRider { _id:string; phoneNumber:string; aadharNumber:string; drivingLicenseNumber:string; picture:string; isVerified:boolean; isAvailble:boolean; }

const RiderDashboard = () => {
  const { user, setIsAuth, setUser } = useAppData(); const { socket } = useSocket();
  const [profile,setProfile]=useState<IRider|null>(null); const [loading,setLoading]=useState(true); const [toggling,setToggling]=useState(false); const [incomingOrders,setIncomingOrders]=useState<string[]>([]); const [currentOrder,setCurrentOrder]=useState<IOrder|null>(null); const [audioUnlocked,setAudioUnlocked]=useState(false); const audioRef=useRef<HTMLAudioElement|null>(null);
  const [phoneNumber,setPhoneNumber]=useState(""); const [aadharNumber,setAadharNumber]=useState(""); const [drivingLicenseNumber,setDrivingLicenseNumber]=useState(""); const [image,setImage]=useState<File|null>(null); const [submitting,setSubmitting]=useState(false);
  const headers={Authorization:`Bearer ${localStorage.getItem("token")}`};

  useEffect(()=>{audioRef.current=new Audio(audio);audioRef.current.preload="auto";},[]);
  const unlockAudio=async()=>{try{if(!audioRef.current)return;await audioRef.current.play();audioRef.current.pause();audioRef.current.currentTime=0;setAudioUnlocked(true);toast.success("Delivery alerts enabled");}catch{toast.error("Tap again to enable sound");}};
  const fetchProfile=async()=>{try{const {data}=await axios.get(`${riderService}/api/rider/myprofile`,{headers});setProfile(data||null);}catch{setProfile(null);}finally{setLoading(false);}};
  const fetchCurrentOrder=async()=>{try{const {data}=await axios.get(`${riderService}/api/rider/order/current`,{headers});setCurrentOrder(data.order||null);}catch{setCurrentOrder(null);}};
  useEffect(()=>{if(user?.role==="rider"){fetchProfile();fetchCurrentOrder();}else setLoading(false);},[user?._id]);

  useEffect(()=>{if(!socket)return;const onOrderAvailable=({orderId}:{orderId:string})=>{setIncomingOrders((prev)=>prev.includes(orderId)?prev:[...prev,orderId]);if(audioUnlocked&&audioRef.current){audioRef.current.currentTime=0;audioRef.current.play().catch(()=>{});}window.setTimeout(()=>setIncomingOrders((prev)=>prev.filter((id)=>id!==orderId)),10000);};socket.on("order:available",onOrderAvailable);return()=>{socket.off("order:available",onOrderAvailable);};},[socket,audioUnlocked]);

  const getPosition=()=>new Promise<GeolocationPosition>((resolve,reject)=>{if(!navigator.geolocation){reject(new Error("Geolocation is not supported"));return;}navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:10000,maximumAge:5000});});

  const toggleAvailability=async()=>{try{setToggling(true);const pos=await getPosition();const {data}=await axios.patch(`${riderService}/api/rider/toggle`,{isAvailble:!profile?.isAvailble,latitude:pos.coords.latitude,longitude:pos.coords.longitude},{headers});setProfile(data.rider);toast.success(data.message);}catch(error){toast.error(axios.isAxiosError(error)?error.response?.data?.message||"Could not update availability":error instanceof Error?error.message:"Location access is required");}finally{setToggling(false);}};

  const handleSubmit=async()=>{if(!/^\d{10}$/.test(phoneNumber)){toast.error("Enter a valid 10-digit phone number");return;}if(!/^\d{12}$/.test(aadharNumber)){toast.error("Enter a valid 12-digit Aadhaar number");return;}if(!drivingLicenseNumber.trim()||!image){toast.error("Driving licence and profile image are required");return;}try{setSubmitting(true);const pos=await getPosition();const formData=new FormData();formData.append("phoneNumber",phoneNumber);formData.append("aadharNumber",aadharNumber);formData.append("drivingLicenseNumber",drivingLicenseNumber.trim());formData.append("latitude",String(pos.coords.latitude));formData.append("longitude",String(pos.coords.longitude));formData.append("file",image);const {data}=await axios.post(`${riderService}/api/rider/new`,formData,{headers});toast.success(data.message);await fetchProfile();}catch(error){toast.error(axios.isAxiosError(error)?error.response?.data?.message||"Could not create rider profile":error instanceof Error?error.message:"Location access is required");}finally{setSubmitting(false);}};

  const logout=()=>{localStorage.removeItem("token");setIsAuth(false);setUser(null);toast.success("Logged out");};
  const refreshAfterRequest=()=>{setIncomingOrders([]);fetchProfile();fetchCurrentOrder();};

  if(user?.role!=="rider")return <div className="flex min-h-[60vh] items-center justify-center text-sm font-semibold text-slate-400">This account is not registered as a rider.</div>;
  if(loading)return <div className="flex min-h-screen items-center justify-center text-sm font-semibold text-slate-400">Loading rider workspace...</div>;

  if(!profile)return <main className="cm-page min-h-screen pb-12"><header className="border-b border-white/10 bg-[#0f1319]/88"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4 sm:px-6"><BrandLogo/><button className="cm-secondary !p-2.5" onClick={logout}><BiLogOut/></button></div></header><div className="mx-auto grid max-w-5xl gap-6 px-4 py-8 sm:px-6 lg:grid-cols-[0.8fr_1.2fr]"><section className="rounded-[2rem] bg-[#0a0d12] p-7 text-white"><BiCycling className="text-5xl text-orange-400"/><p className="mt-6 text-xs font-bold uppercase tracking-[0.18em] text-orange-300">QuickDish Partner</p><h1 className="mt-2 text-3xl font-black">Deliver locally. Earn per trip.</h1><p className="mt-3 text-sm leading-6 text-slate-300">Complete your profile once. An admin will verify it before you can receive nearby delivery requests.</p></section><section className="cm-card p-6 sm:p-8"><h2 className="text-2xl font-black text-slate-100">Delivery partner profile</h2><div className="mt-6 space-y-4"><input className="cm-input" inputMode="numeric" maxLength={12} placeholder="12-digit Aadhaar number" value={aadharNumber} onChange={(e)=>setAadharNumber(e.target.value.replace(/\D/g,"").slice(0,12))}/><input className="cm-input" inputMode="numeric" maxLength={10} placeholder="10-digit contact number" value={phoneNumber} onChange={(e)=>setPhoneNumber(e.target.value.replace(/\D/g,"").slice(0,10))}/><input className="cm-input" placeholder="Driving licence number" value={drivingLicenseNumber} onChange={(e)=>setDrivingLicenseNumber(e.target.value)}/><label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-white/15 bg-[#11161d] p-4 text-sm font-semibold text-slate-400 hover:border-orange-300 hover:bg-orange-500/10"><BiImageAdd className="text-xl text-orange-500"/>{image?image.name:"Upload a clear profile photo"}<input type="file" accept="image/*" hidden onChange={(e)=>setImage(e.target.files?.[0]||null)}/></label><button className="cm-primary w-full" disabled={submitting} onClick={handleSubmit}>{submitting?"Submitting...":"Submit for verification"}</button></div></section></div></main>;

  return <main className="cm-page min-h-screen pb-12"><header className="border-b border-white/10 bg-[#0f1319]/88 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6"><BrandLogo/><div className="flex items-center gap-2"><span className="hidden rounded-full bg-orange-500/10 px-3 py-1.5 text-xs font-bold text-orange-700 sm:inline">Rider Workspace</span><button className="cm-secondary !p-2.5" onClick={logout}><BiLogOut/></button></div></div></header>
    <div className="mx-auto max-w-6xl space-y-5 px-4 py-7 sm:px-6"><section className="cm-card p-5 sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><img src={profile.picture} className="h-20 w-20 rounded-2xl object-cover ring-4 ring-orange-50" alt={user?.name||"Rider"}/><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Delivery partner</p><h1 className="mt-1 text-2xl font-black text-slate-100">{user?.name}</h1><p className="mt-1 text-sm text-slate-400">{profile.phoneNumber}</p><div className="mt-3 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${profile.isVerified?"bg-emerald-500/10 text-emerald-700":"bg-amber-500/10 text-amber-700"}`}><BiCheckShield className="mr-1 inline"/>{profile.isVerified?"Verified":"Verification pending"}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${profile.isAvailble?"bg-orange-500/10 text-orange-700":"bg-[#1c232d] text-slate-400"}`}>{profile.isAvailble?"Online":"Offline"}</span></div></div>{profile.isVerified&&!currentOrder&&<button onClick={toggleAvailability} disabled={toggling} className={profile.isAvailble?"cm-secondary":"cm-primary"}>{toggling?"Updating...":profile.isAvailble?"Go offline":"Go online"}</button>}</div>{!profile.isVerified&&<p className="mt-4 rounded-2xl bg-amber-500/10 p-3 text-sm font-medium text-amber-800">You can go online after an admin verifies this profile.</p>}{profile.isVerified&&!currentOrder&&<p className="mt-4 flex items-start gap-2 rounded-2xl bg-[#11161d] p-3 text-sm text-slate-400"><BiMapPin className="mt-0.5 shrink-0 text-orange-500"/>Be within roughly 500 m of an active restaurant hotspot before going online to receive requests.</p>}</section>

      {!audioUnlocked&&<section className="flex flex-col gap-3 rounded-2xl border border-orange-400/15 bg-orange-500/10 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#171c24] text-xl text-orange-500"><BiBell/></span><div><p className="font-bold text-slate-100">Enable delivery alerts</p><p className="text-sm text-slate-400">Browsers require one tap before QuickDish can play request sounds.</p></div></div><button className="cm-secondary" onClick={unlockAudio}>Enable sound</button></section>}

      {profile.isAvailble&&incomingOrders.length>0&&<section><h2 className="text-lg font-black text-slate-100">Incoming deliveries</h2><div className="mt-3 grid gap-4 md:grid-cols-2">{incomingOrders.map((id)=><RiderOrderRequest key={id} orderId={id} onAccepted={refreshAfterRequest}/>)}</div></section>}
      {currentOrder&&<section className="grid gap-5 lg:grid-cols-[0.72fr_1.28fr] lg:items-start"><RiderCurrentOrder order={currentOrder} onStatusUpdate={()=>{fetchCurrentOrder();fetchProfile();}}/><RiderOrderMap order={currentOrder}/></section>}
      {!currentOrder&&profile.isVerified&&<section className="cm-card p-8 text-center"><BiCycling className="mx-auto text-5xl text-orange-400"/><h2 className="mt-3 text-xl font-black text-slate-100">{profile.isAvailble?"Waiting for a nearby delivery":"You are currently offline"}</h2><p className="mt-2 text-sm text-slate-400">{profile.isAvailble?"Keep this tab open. New requests will appear here in real time.":"Go online when you are ready to accept delivery requests."}</p></section>}
    </div>
  </main>;
};

export default RiderDashboard;
